import * as fs from 'fs/promises';
import * as path from 'path';
import { DeckAnalysis, DeckCard } from './types.js';

/**
 * Exports analysis to markdown format
 */
export async function exportToMarkdown(
  analysis: DeckAnalysis,
  cards: DeckCard[],
  outputPath: string
): Promise<void> {
  const markdown = generateMarkdown(analysis, cards);
  await fs.writeFile(outputPath, markdown, 'utf-8');
  console.log(`✅ Exported to: ${outputPath}`);
}

/**
 * Generates markdown content from analysis
 */
function generateMarkdown(analysis: DeckAnalysis, cards: DeckCard[]): string {
  const lines: string[] = [];
  const date = new Date().toLocaleDateString();

  lines.push('# MTG Deck Analysis Report');
  lines.push('');
  lines.push(`**Generated:** ${date}`);
  lines.push('');

  // Deck List
  lines.push('## Deck List');
  lines.push('');
  const totalCards = cards.reduce((sum, c) => sum + c.quantity, 0);
  lines.push(`Total Cards: ${totalCards}`);
  lines.push('');
  lines.push('```');
  for (const { quantity, name } of cards) {
    lines.push(`${quantity} ${name}`);
  }
  lines.push('```');
  lines.push('');

  // Archetype
  lines.push('## Archetype');
  lines.push('');
  lines.push(analysis.archetype);
  lines.push('');

  // Bracket Rating
  const stars = '⭐'.repeat(analysis.bracketRating);
  lines.push('## Bracket Rating');
  lines.push('');
  lines.push(`**${analysis.bracketRating}/4** ${stars}`);
  lines.push('');
  lines.push(analysis.bracketReasoning);
  lines.push('');

  // Mana Curve
  lines.push('## Mana Curve Analysis');
  lines.push('');
  lines.push(analysis.manaCurveAnalysis);
  lines.push('');

  // Strengths
  lines.push('## Strengths');
  lines.push('');
  analysis.strengths.forEach((strength, i) => {
    lines.push(`${i + 1}. ${strength}`);
  });
  lines.push('');

  // Weaknesses
  lines.push('## Weaknesses');
  lines.push('');
  analysis.weaknesses.forEach((weakness, i) => {
    lines.push(`${i + 1}. ${weakness}`);
  });
  lines.push('');

  // Weak Point Analysis
  if (analysis.weakPoints && analysis.weakPoints.length > 0) {
    lines.push('## Weak Point Analysis');
    lines.push('');
    const severityEmoji: Record<string, string> = {
      critical: '🔴',
      high: '🟠',
      moderate: '🟡',
      low: '🟢'
    };
    analysis.weakPoints.forEach((wp) => {
      const emoji = severityEmoji[wp.severity] || '⚪';
      lines.push(`### ${emoji} ${wp.category} (${wp.severity.toUpperCase()})`);
      lines.push('');
      lines.push(`**Issue:** ${wp.issue}`);
      lines.push('');
      lines.push(`**Impact:** ${wp.impact}`);
      lines.push('');
    });
  }

  // Upgrade Path Analysis
  if (analysis.upgradePathAnalysis) {
    lines.push('## 🛠️ Upgrade Path Roadmap');
    lines.push('');
    lines.push(`**🎯 PRIMARY FOCUS:** ${analysis.upgradePathAnalysis.primaryWeakPoint}`);
    lines.push('');

    analysis.upgradePathAnalysis.budgetBreakpoints.forEach(tier => {
      lines.push(`### 💰 ${tier.budget}`);
      lines.push('');
      lines.push(`**Expected Impact:** ${tier.expectedImpact}`);
      lines.push('');
      lines.push('**Recommended Cards:**');
      tier.recommendedUpgrades.forEach(card => {
        lines.push(`- ${card}`);
      });
      lines.push('');
    });
  }

  // Existing Combos
  if (analysis.existingCombos.length > 0) {
    lines.push('## Existing Combos & Synergies');
    lines.push('');
    analysis.existingCombos.forEach((combo, i) => {
      lines.push(`${i + 1}. ${combo}`);
    });
    lines.push('');
  }

  // Potential Combos
  if (analysis.potentialCombos.length > 0) {
    lines.push('## Potential Combos to Consider');
    lines.push('');
    analysis.potentialCombos.forEach((combo, i) => {
      lines.push(`${i + 1}. ${combo}`);
    });
    lines.push('');
  }

  // Card Suggestions
  if (analysis.cardSuggestions.length > 0) {
    lines.push('## Card Suggestions (Sorted by Price)');
    lines.push('');
    analysis.cardSuggestions.forEach((suggestion, i) => {
      const priceDisplay = suggestion.price !== undefined
        ? `${suggestion.priceTier} ($${suggestion.price.toFixed(2)})`
        : suggestion.priceTier || '?';
      lines.push(`${i + 1}. **${suggestion.card}** — ${priceDisplay}`);
      lines.push(`   - ${suggestion.reasoning}`);
      lines.push('');
    });
  }

  // Overall Assessment
  lines.push('## Overall Assessment');
  lines.push('');
  lines.push(analysis.overallAssessment);
  lines.push('');

  lines.push('---');
  lines.push('*Generated by MTG Deck Analyzer powered by Claude*');

  return lines.join('\n');
}

/**
 * Exports analysis to JSON format
 */
export async function exportToJSON(
  analysis: DeckAnalysis,
  cards: DeckCard[],
  outputPath: string
): Promise<void> {
  const data = {
    timestamp: new Date().toISOString(),
    deck: cards.map(({ quantity, name }) => ({ quantity, name })),
    analysis,
  };

  await fs.writeFile(outputPath, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`✅ Exported to: ${outputPath}`);
}
